config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"
  resources :users  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :addresses , inverse_of: :user
	accepts_nested_attributes_for :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:city, :area, :street, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show 
    @user = User.find(params[:id])
  end 

  def new 
    @user = User.new 
  end 

  def create 
    @user = User.new(user_params)
    if @user.save 
      UserMailer.with(user: @user).welcome_email.deliver_now
      redirect_to @user 

    else 
      render :new , status: :unprocessable_entity
    end 
  end 


  def edit 
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user 
    else 
      render :edit, status: :unprocessable_entity
    end 
  end 

  def destroy
    @user = User.find(params[:id])
    @user.destroy 

    redirect_to @user 
  end

  private 

  def user_params 
    params.require(:user).permit(:name , :mobno, addresses_attributes: [:id,:city, :area, :street , :_destroy])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_address_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :area %>
    <br>
    <%= f.text_field :area %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <br>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.check_box :done %>
    <%= f.label :done %>
  </div>
  <%= link_to_remove_association "remove task", f %>
</div>

app/views/addresses/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :city %>
    <br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :Area %>
    <br>
    <%= f.text_field :area %>
  </div>

  <h3> Address </h3>
  <div id="addresses">
    <%= f.fields_for :addresses do |add| %>
      <%= render 'address_fields', f: task %>
  </div>

  <div class="links">
    <%= link_to_add_association 'add address', f, :addresses %>
    <%= f.submit %>
  </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coconproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_address_fields.html.erb
<center>
  <div class="nested-fields">
     <div class="field">
      <%= f.label :city %>
      <br>
      <%= f.text_field :city %>
    </div>
    
    <div class="field">
      <%= f.label :area %>
      <br>
      <%= f.text_field :area %>
    </div>

    <div class="field">
      <%= f.label :street %>
      <br>
      <%= f.text_field :street %>
    </div>
    <%= link_to_remove_association "remove task", f %>
  </div> 
</center>

app/views/users/edit.html.erb
<center>
<h4>User Creation</h4>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :mobno %>
    <br>
    <%= f.text_field :mobno %>
  </div>

  <h3> Address </h3>
  <div id="addresses">
    <%= f.fields_for :addresses do |add| %>
      <%= render 'address_fields', f: task %>
    <% end %>
	  <div class="links">
	    <%= link_to_add_association 'add address', f, :addresses %>
	  </div>
  </div>
  <%= f.submit %>
<% end %>
</center>

app/views/users/index.html.erb
<center>
	<h1>HelloUsers</h1>
	<% @users.each do |user| %>
	<br>
		<span style="color:darkmagenta;"><%= user.name %></span>
		<br>
		<%= user.mobno %>
		<br>

		<% user.addresses.each do |address| %>
		<%= address.city %>
		<br>
		<%= address.area %>
		<br>
		<%= address.street %>
		<% end %>
		<br>
		<%= link_to "ShowUser", user_path(user), class:"btn btn-outline-warning btn-sm" %>
	|| <%= link_to "DEleteUser", user_path(user), method: :delete , class:"btn btn-outline-danger btn-sm" %>
	<hr>
	<% end %>
	<br>
	<%= link_to "NewForm" , new_user_path, class:"btn btn-info" %>
</center>

app/views/users/new.html.erb
<center>
<h4>User Creation</h4>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :mobno %>
    <br>
    <%= f.text_field :mobno %>
  </div>

  <h3> Address </h3>
  <div id="addresses">
    <%= f.fields_for :addresses do |add| %>
      <%= render 'address_fields', f: task %>
    <% end %>
	  <div class="links">
	    <%= link_to_add_association 'add address', f, :addresses %>
	  </div>
  </div>
  <%= f.submit %>
<% end %>
</center>

app/views/users/show.html.erb
<center>
	<h1 style="color: darkolivegreen;">Show Page</h1>
	<br>
	<h3><strong style="color:orangered;"><%= @user.name %></strong></h3>
	<%= @user.mobno %>
	
	<% @user.addresses.each do |address| %>
		<%= address.city %>
		<br>
		<%= address.area %>
		<br>
		<%= address.street %>
		<br>
	<% end %>

	<br>
	<%= link_to "EDitUser", edit_user_path(@user), class:"btn btn-outline-dark btn-sm" %>
	|| <%= link_to "DEleteUser", user_path(@user), method: :delete , class:"btn btn-outline-dark btn-sm" %>

</center>
<%= link_to "back", users_path %>